name: Display results of math work

on:
  workflow_call: {}

jobs:
  display_results:
    name: Display results
    runs-on: ubuntu-latest
    steps:
      - name: Download math result from caller
        uses: actions/download-artifact@v3.0.1
        with:
          name: homework
      - name: Print the final result
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value
